# Name and metadata of your task
task_name: 'task name'
author: 'Koii'
description: 'description'
repositoryUrl: 'https://github.com/koii-network/task-template' #replace with your own repo url
imageUrl: 'imageUrl'

# task_executable_network : DEVELOPMENT, ARWEAVE or IPFS
# IPFS is the default value, as the CLI automatically manages the upload process via the Koii Storage SDK.
task_executable_network: 'IPFS'

# task_audit_program: Path to your executable webpack if the selected network is IPFS and in case of DEVELOPMENT name it as main
task_audit_program: 'dist/main.js'

# round_time: The total duration of your task, measured in slots (with each slot approximately equal to 408ms)
round_time: 1500
audit_window: 350
submission_window: 350

# minimum_stake_amount: The minimum amount of KOII that a user must stake in order to participate in the task
minimum_stake_amount: 1.9

# total_bounty_amount cannot be grater than bounty_amount_per_round
# total bounty_amount: The total bounty amount that will be distributed to the task. (Not accepted in case of update task)
total_bounty_amount: 100
bounty_amount_per_round: 100

# allowed_failed_distributions: Number of times re-submission is allowed for the distribution list in case of an audit.
allowed_failed_distributions: 3

# space: Space in MBs for the account size, that holds the task data.
space: 1

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer the type,value, description format shown below

requirementsTags:
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

# OPTIONAL variables variables for creating task / REQUIRED variables for update task

# ONLY provide the task_id and migrationDescription if you are updating the task otherwise leave blank
# task_id: Previous task id
task_id: ''

# migrationDescription: Provide the description for changes made in new version of task
migrationDescription: ''
