# See the config-task.yml file in the task template repository for the full configuration

requirementsTags:
  - type: CPU
    value: "4-core"
  - type: RAM
    value: "5 GB"
  - type: STORAGE
    value: "5 GB"
  - type: TASK_VARIABLE
    value: "SECRET"
    description: "The secret you want to tell other nodes!"
  - type: ADDON
    value: "REQUIRE_INTERNET"
